"""
Django settings for vcsc project.

Generated by 'django-admin startproject' using Django 4.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from __future__ import absolute_import, unicode_literals
##from google.cloud import storage
##from google.oauth2 import service_account
##from django.core.files.storage import default_storage

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from dotenv import load_dotenv
import json

import dropbox 

#env = os.environ.copy()
load_dotenv()

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    "menus",
    "site_settings",
    "streams",
    "flex",
    "people",
    "subbanners",
    "research",
    "wagtail.contrib.forms",
    "wagtail.contrib.modeladmin",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.contrib.sitemaps",
    "wagtail.contrib.routable_page",
    "wagtail.api.v2",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtailmenus",
    "modelcluster",
    "taggit",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django.contrib.staticfiles",

    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    ##"whitenoise.runserver_nostatic",

    "fontawesomefree",
    "rest_framework",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    
    "django.middleware.security.SecurityMiddleware",
    ##"whitenoise.middleware.WhiteNoiseMiddleware",
]

##DEFAULT_FILE_STORAGE = "storages.backends.dropbox.DropboxStorage"
DEFAULT_FILE_STORAGE = "storages.backends.dropbox.DropBoxStorage"

os.environ.get('DROPBOX_OAUTH2_TOKEN') = DROPBOX_OAUTH2_TOKEN
os.environ.get('DROPBOX_APP_KEY') = DROPBOX_APP_KEY
os.environ.get('DROPBOX_APP_SECRET') = DROPBOX_APP_SECRET
os.environ.get('DROPBOX_OAUTH2_REFRESH_TOKEN') = DROPBOX_OAUTH2_REFRESH_TOKEN

ROOT_URLCONF = "vcsc.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail.contrib.settings.context_processors.settings",
                "wagtailmenus.context_processors.wagtailmenus",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

WSGI_APPLICATION = "vcsc.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dbpsql',
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': '',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/4.0/ref/contrib/staticfiles/#manifeststaticfilesstorage

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

## With Django < 4.2:
##STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
##STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# GS_CREDENTIALS = json.loads(os.environ.get('GOOGLE_CREDENTIALS'))

#credential_path = os.path.join(BASE_DIR, 'google-credentials.json')
#os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credential_path

# django < 4.2
#DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
# django < 4.2
#STATICFILES_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"

## With Django 4.2+:
##STORAGES = {
##    # ...
##    "staticfiles": {
##        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
##    },
##}

# Prior to django-storages[google]:
#STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

# django < 4.2
#STATICFILES_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
# django >= 4.2:
# STORAGES = {"staticfiles": {"BACKEND": "storages.backends.gcloud.GoogleCloudStorage"}}

# django < 4.2
#DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
# django >= 4.2
#STORAGES = {"default": {"BACKEND": "storages.backends.gcloud.GoogleCloudStorage"}}

#GS_BUCKET_NAME = "vcsc-bucket"
#GS_DEFAULT_ACL = "publicRead"

## From StackOverflow: https://stackoverflow.com/questions/47446480/how-to-use-google-api-credentials-json-on-heroku

# the json credentials stored as env variable
#json_str = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS')  ##GOOGLE_APPLICATION_CREDENTIALS

# project name
# gcp_project = os.environ.get('GCP_PROJECT') 

#CREDENTIALS_DICT = {
#    "type": os.environ["TYPE"],
#    "project_id": os.environ["PROJECT_ID"],
#    "private_key_id": os.environ["PRIVATE_KEY_ID"],
#    "private_key": os.environ["PRIVATE_KEY"].replace('\\n', '\n'),
#    "client_email": os.environ["CLIENT_EMAIL"],
#    "client_id": os.environ["CLIENT_ID"],
#    "auth_uri": os.environ["AUTH_URI"],
#    "token_uri": os.environ["TOKEN_URI"],
#    "auth_provider_x509_cert_url": os.environ["AUTH_PROVIDER_X509_CERT_URL"],
#    "client_x509_cert_url": os.environ["CLIENT_X509_CERT_URL"]
#}
#print(CREDENTIALS_DICT)
#CREDENTIALS = str(CREDENTIALS_DICT)
#CREDENTIALS = CREDENTIALS.replace("\'", "\"")
#print(CREDENTIALS)

# generate json - if there are errors here remove newlines
#json_data = json.loads(json_str)
#with open(json_str, 'r') as j:
#     json_data = json.loads(j.read())
#with open(os.environ.get('GOOGLE_CREDENTIALS'), encoding='utf-8', errors='ignore') as j:
#     json_data = json.load(j, strict=False)
#json_data = json.loads(CREDENTIALS)
# the private_key needs to replace \n parsed as string literal with escaped newlines
#json_data['private_key'] = json_data['private_key']

# use service_account to generate credentials object
#credentials = service_account.Credentials.from_service_account_info(
#    json_data)

# pass credentials AND project name to new client object
#storage_client = storage.Client(
#    project=gcp_project, credentials=credentials)

# use service_account to generate credentials object
# my_credentials = service_account.Credentials.from_service_account_info(CREDENTIALS) 

# pass credentials AND project name to new client object
#storage_client = storage.Client(project=gcp_project, credentials=my_credentials)


# Wagtail settings
WAGTAIL_SITE_NAME = "vcsc"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Default RichText Features
# see 3:28, https://www.youtube.com/watch?v=ei7ot_Wry3o
# see also https://docs.wagtail.org/en/stable/advanced_topics/customisation/page_editing_interface.html

RICHTEXT_BLOCKTYPES = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ul', 'ol']
RICHTEXT_INLINESTYLES = ['bold', 'italic']
RICHTEXT_ENTITIES = ['image', 'embed', 'link', 'document-link']
RICHTEXT_MISC = ['hr', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote']

ALL_RICHTEXT_FEATURES = (
    RICHTEXT_BLOCKTYPES + 
    RICHTEXT_INLINESTYLES + 
    RICHTEXT_ENTITIES + 
    RICHTEXT_MISC
)

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none" ##mandatory
##ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/login/'
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_USERNAME_BLACKLIST = ["admin", "god"]
ACCOUNT_USERNAME_MIN_LENGTH = 3
