# Generated by Django 4.1.4 on 2022-12-29 17:06

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subbanners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbannerpage',
            name='lead_text_p',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short lead text, if needed'),
        ),
    ]
