# Generated by Django 4.1.4 on 2022-12-27 18:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=500)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify research items by this lab', max_length=500, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Research Lab',
                'verbose_name_plural': 'Research Labs',
                'ordering': ['lab_name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPressListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Research press listing page',
                'verbose_name_plural': 'Research press listing pages',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ResearchPublicationsListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Research publications listing page',
                'verbose_name_plural': 'Research publications listing pages',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ResearchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_type', models.CharField(max_length=500)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify research items by type (publications, press, or media)', max_length=500, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Research Type',
                'verbose_name_plural': 'Research Types',
                'ordering': ['research_type'],
            },
        ),
        migrations.CreateModel(
            name='ResearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=500, null=True)),
                ('authors', modelcluster.fields.ParentalManyToManyField(blank=True, to='people.peopleperson')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('research_labs', modelcluster.fields.ParentalManyToManyField(to='research.researchlab')),
                ('research_type', modelcluster.fields.ParentalManyToManyField(blank=True, to='research.researchtype')),
            ],
            options={
                'verbose_name': 'Research Item',
                'verbose_name_plural': 'Research Items',
            },
        ),
    ]
