# Generated by Django 4.1.4 on 2022-12-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlab',
            name='lab_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
