# Generated by Django 4.1.4 on 2023-01-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchlab_lab_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchlab',
            name='lab_website',
        ),
    ]
