# Generated by Django 4.1.4 on 2023-01-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('research', '0005_remove_researchlab_lab_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlab',
            name='external_website',
            field=models.URLField(blank=True, help_text="Add lab website URL here (unless lab's website is part of this VCSC website, in which case, see the field below."),
        ),
        migrations.AddField(
            model_name='researchlab',
            name='internal_page',
            field=models.ForeignKey(blank=True, help_text='If lab website is a page on the VCSC website, add the link here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
