# Generated by Django 4.1.4 on 2023-01-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('research', '0006_researchlab_external_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlab',
            name='lab_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
