# Generated by Django 4.1.4 on 2023-01-05 17:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('research', '0007_researchlab_lab_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroupListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('lead_text', wagtail.fields.RichTextField(blank=True, help_text='Short lead text, if needed')),
            ],
            options={
                'verbose_name': 'Research Group Listing Page',
                'verbose_name_plural': 'Research Group Listing Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
