# Generated by Django 4.1.4 on 2023-01-05 17:43

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_researchgrouplistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlab',
            name='lab_bio',
            field=wagtail.fields.RichTextField(blank=True, help_text='Brief lab bio (please limit number of hyperlinks included, as these need to be maintained and tend to go stale)'),
        ),
    ]
