# Generated by Django 4.1.4 on 2023-01-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_researchlab_group_leads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchlab',
            old_name='group_leads',
            new_name='authors',
        ),
    ]
