# Generated by Django 4.1.4 on 2023-01-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_rename_group_leads_researchlab_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchlab',
            old_name='authors',
            new_name='group_leads',
        ),
    ]
