# Generated by Django 4.1.4 on 2023-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_rename_authors_researchlab_group_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlab',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
