# Generated by Django 4.1.4 on 2023-02-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_researchlab_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchitem',
            options={'ordering': ['-date'], 'verbose_name': 'Research Item', 'verbose_name_plural': 'Research Items'},
        ),
        migrations.RemoveField(
            model_name='researchitem',
            name='research_type',
        ),
        migrations.AddField(
            model_name='researchitem',
            name='research_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.researchtype'),
        ),
    ]
