# Generated by Django 4.1.4 on 2022-12-27 13:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplePersonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('add_person', wagtail.snippets.blocks.SnippetChooserBlock(target_model='people.PeoplePerson', template='streams/person_block.html'))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'verbose_name': 'Person page',
                'verbose_name_plural': 'Person pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PeopleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=500)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify people by role', max_length=500, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='PeoplePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Full name')),
                ('last_name', models.CharField(max_length=300, null=True, verbose_name='Last name only')),
                ('slug', models.SlugField(allow_unicode=True, help_text="Please enter person's name as first-last (all lowercase, using in place of spaces)", max_length=200, verbose_name='slug')),
                ('title', models.CharField(max_length=500, null=True)),
                ('bio', wagtail.fields.RichTextField(blank=True, help_text='Job title')),
                ('external_website', models.URLField(blank=True)),
                ('authors', modelcluster.fields.ParentalManyToManyField(blank=True, to='people.peopleperson')),
                ('internal_page', models.ForeignKey(blank=True, help_text='Create and then select internal page for this person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('person_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('person_role', modelcluster.fields.ParentalManyToManyField(to='people.peoplerole')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['last_name'],
            },
        ),
    ]
