# Generated by Django 4.1.4 on 2022-12-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_peoplelistingpagecore_peopleperson_research_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleperson',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
