# Generated by Django 4.1.4 on 2022-12-28 19:03

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        ('people', '0003_peopleperson_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleperson',
            name='research_labs',
            field=modelcluster.fields.ParentalManyToManyField(to='research.researchlab'),
        ),
    ]
