# Generated by Django 4.1.4 on 2022-12-28 19:05

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        ('people', '0004_peopleperson_research_labs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleperson',
            name='research_labs',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='research.researchlab'),
        ),
    ]
