# Generated by Django 4.1.4 on 2022-12-28 19:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('people', '0005_alter_peopleperson_research_labs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleListingPageStudent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'People listing page: Students',
                'verbose_name_plural': 'People listing pages: Students',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PeoplePersonPageStudents',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('add_person', wagtail.snippets.blocks.SnippetChooserBlock(target_model='people.PeoplePerson', template='streams/person_block_student.html'))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'verbose_name': 'Person page (students)',
                'verbose_name_plural': 'Person pages (students)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
