# Generated by Django 4.1.4 on 2022-12-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_peopleperson_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleperson',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='strava',
            field=models.URLField(blank=True),
        ),
    ]
