# Generated by Django 4.1.4 on 2022-12-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_peopleperson_github_peopleperson_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleperson',
            name='arxiv',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='gitlab',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='google_scholar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='orcid',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='research_gate',
            field=models.URLField(blank=True),
        ),
    ]
