# Generated by Django 4.1.4 on 2022-12-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_peopleperson_arxiv_peopleperson_gitlab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepersonpagestudents',
            name='lead_text',
            field=models.CharField(blank=True, help_text='Short lead text, if needed', max_length=140),
        ),
    ]
