# Generated by Django 4.1.4 on 2022-12-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_peoplepersonpagestudents_lead_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplepersonpagestudents',
            name='lead_text',
        ),
        migrations.AddField(
            model_name='peoplelistingpagestudent',
            name='lead_text',
            field=models.CharField(blank=True, help_text='Short lead text, if needed', max_length=140),
        ),
    ]
