# Generated by Django 4.1.4 on 2022-12-29 16:40

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_remove_peoplepersonpagestudents_lead_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplelistingpagestudent',
            name='lead_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short lead text, if needed'),
        ),
    ]
