# Generated by Django 4.1.4 on 2022-12-29 16:59

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_alter_peoplelistingpagestudent_lead_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplelistingpagecore',
            name='lead_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short lead text, if needed'),
        ),
    ]
