# Generated by Django 4.1.4 on 2022-12-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_peoplelistingpagecore_lead_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplelistingpagecore',
            options={'verbose_name': 'People listing page: Core Team, Postdocs', 'verbose_name_plural': 'People listing pages: Core Team, Postdocs'},
        ),
    ]
