# Generated by Django 4.1.4 on 2022-12-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_alter_peoplelistingpagecore_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplelistingpagestudent',
            options={'verbose_name': 'People listing page: Students (PhD and MS/AMP)', 'verbose_name_plural': 'People listing pages: Students (PhD and MS/AMP)'},
        ),
        migrations.AlterModelOptions(
            name='peoplepersonpage',
            options={'verbose_name': 'Person page: Core Team, Postdocs', 'verbose_name_plural': 'Person pages: Core Team, Postdocs'},
        ),
        migrations.AlterModelOptions(
            name='peoplepersonpagestudents',
            options={'verbose_name': 'Person page: Students (PhD and MS/AMP)', 'verbose_name_plural': 'Person pages: Students (PhD and MS/AMP)'},
        ),
    ]
