# Generated by Django 4.1.4 on 2022-12-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_peoplelistingpagepostdoc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplepersonpage',
            options={'verbose_name': 'Person page: Core Team, Postdocs', 'verbose_name_plural': 'Person pages: Core Team, Postdocs'},
        ),
    ]
