# Generated by Django 4.1.4 on 2022-12-29 20:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('people', '0019_alter_peoplepersonpage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleListingPageExternalFaculty',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('lead_text', wagtail.fields.RichTextField(blank=True, help_text='Short lead text, if needed')),
            ],
            options={
                'verbose_name': 'People listing page: External Faculty',
                'verbose_name_plural': 'People listing pages: External Faculty',
            },
            bases=('wagtailcore.page',),
        ),
    ]
