# Generated by Django 4.1.4 on 2022-12-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_peoplelistingpageexternalfaculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplepersonpage',
            options={'verbose_name': 'Person page: Core Team, Postdocs, External Faculty', 'verbose_name_plural': 'Person pages: Core Team, Postdocs, External Faculty'},
        ),
    ]
