# Generated by Django 4.1.4 on 2022-12-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_alter_peoplepersonpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleperson',
            name='academia',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='philpapers',
            field=models.URLField(blank=True),
        ),
    ]
