# Generated by Django 4.1.4 on 2022-12-30 16:38

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_peopleperson_academia_peopleperson_philpapers'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleperson',
            name='current_employment',
            field=wagtail.fields.RichTextField(blank=True, help_text='For alumni only: current employment'),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='thesis_topic',
            field=wagtail.fields.RichTextField(blank=True, help_text='For alumni only: thesis topic'),
        ),
    ]
