# Generated by Django 4.1.4 on 2022-12-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_peopleperson_current_employment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplelistingpagecore',
            options={'verbose_name': 'People listing page: Alumni', 'verbose_name_plural': 'People listing pages: Alumni'},
        ),
        migrations.AlterModelOptions(
            name='peoplepersonpage',
            options={'verbose_name': 'Person page: Core Team, Postdocs, External Faculty, Alumni', 'verbose_name_plural': 'Person pages: Core Team, Postdocs, External Faculty, Alumni'},
        ),
    ]
