# Generated by Django 4.1.4 on 2022-12-30 16:55

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_peoplelistingpagealumni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleperson',
            name='current_employment',
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='current_employer',
            field=wagtail.fields.RichTextField(blank=True, help_text='For alumni only: current employer'),
        ),
    ]
