# Generated by Django 4.1.4 on 2022-12-30 16:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_remove_peopleperson_current_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleperson',
            name='current_role',
            field=wagtail.fields.RichTextField(blank=True, help_text='For alumni only: current role'),
        ),
    ]
