# Generated by Django 4.1.4 on 2022-12-30 17:01

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_peopleperson_current_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleperson',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, help_text='Brief bio (please limit number of hyperlinks included, as these need to be maintained and tend to go stale)'),
        ),
    ]
