# Generated by Django 4.1.4 on 2022-12-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_alter_peopleperson_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleDegreeAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_degree_type', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify alumni degrees (PhD, MS, or BS)', max_length=100, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Alumni Degree Type',
                'verbose_name_plural': 'Alumni Degree Types',
                'ordering': ['alumni_degree_type'],
            },
        ),
        migrations.CreateModel(
            name='PeopleGradYearAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_graduation_year', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify alumni graduation years', verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Alumni Graduation Year',
                'verbose_name_plural': 'Alumni Graduation Years',
                'ordering': ['alumni_graduation_year'],
            },
        ),
    ]
