# Generated by Django 4.1.4 on 2022-12-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_peopledegreealumni_peoplegradyearalumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledegreealumni',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='A slug to identify alumni degrees (Postdoc, PhD, MS, or BS)', max_length=100, verbose_name='slug'),
        ),
    ]
