# Generated by Django 4.1.4 on 2022-12-30 17:23

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_alter_peopledegreealumni_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleperson',
            name='alumni_degree',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='people.peopledegreealumni'),
        ),
        migrations.AddField(
            model_name='peopleperson',
            name='alumni_year',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='people.peoplegradyearalumni'),
        ),
    ]
