# Generated by Django 4.1.4 on 2022-12-30 17:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('people', '0031_peopleperson_alumni_degree_peopleperson_alumni_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplePersonPageAlumni',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('add_person', wagtail.snippets.blocks.SnippetChooserBlock(target_model='people.PeoplePerson', template='streams/person_block_alumni.html'))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'verbose_name': 'Person page: Alumni',
                'verbose_name_plural': 'Person pages: Alumni',
            },
            bases=('wagtailcore.page',),
        ),
    ]
