# Generated by Django 4.1.4 on 2022-12-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_peoplepersonpagealumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleperson',
            name='current_employer',
            field=models.CharField(blank=True, help_text='For alumni only: current employer', max_length=200),
        ),
        migrations.AlterField(
            model_name='peopleperson',
            name='current_role',
            field=models.CharField(blank=True, help_text='For alumni only: current role', max_length=200),
        ),
        migrations.AlterField(
            model_name='peopleperson',
            name='thesis_topic',
            field=models.CharField(blank=True, help_text='For alumni only: thesis topic', max_length=500),
        ),
    ]
