# Generated by Django 4.1.4 on 2023-03-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0035_alter_peoplepersonpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleperson',
            name='mastadon',
            field=models.URLField(blank=True),
        ),
    ]
