# Generated by Django 4.1.4 on 2023-03-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_peopleperson_mastadon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleperson',
            old_name='mastadon',
            new_name='mastodon',
        ),
    ]
